### ISSUE TITLE
Potential Worker Script Issue

### ISSUE THREAD

**Issue by michaelcmelton** [ldez/cubejs#11]
I'm having an issue using it on my own, in my project. I'm returning an importScripts is not a function issue in the Javascript console. I don't know much about worker scripts, so any help would be appreciated. Thanks.

**Comment by ldez** [comment]
Could you provide more information? (Github repo, sample, ...)

**Comment by michaelcmelton** [comment]
For your repo `ldez/cubejs`, I guess i don't know how I need to use it inside a node app. How do I initialize it and everything else?

**Comment by ldez** [comment]
> I'm returning an importScripts is not a function issue in the Javascript console. 

I want to know your code (**your repo**, your context).

```js
const Cubejs = require('cubejs/lib/cube.js');

console.log(Cubejs.random())
console.log(Cubejs.inverse("U R"));
```

```js
const Cubejs = require('cubejs/lib/cube.js');
require('cubejs/lib/solve.js');

Cubejs.initSolver();

const cube01 = new Cubejs();
console.log(cube01.solve());

const cube02 = Cubejs.random();
console.log(cube02.solve());
```

**Comment by ldez** [comment]
WebWorker is for browser because Node doesn't support natively WebWorker.

**Comment by michaelcmelton** [comment]
Makes sense, so I've revamped my code then. Now my [https://github.com/michaelcmelton/speedcubing-timer/blob/master/server.js](server.js) is returning a `cube.scramble is not a function` error 
<img width="556" alt="screen shot 2017-09-02 at 5 11 34 pm" src="https://user-images.githubusercontent.com/21992321/29998788-cec8c87a-9001-11e7-863f-14ecbed39ca7.png">

**Comment by ldez** [comment]
@michaelcmelton https://github.com/michaelcmelton/speedcubing-timer/pull/1
