### ISSUE TITLE
algorithmic/formal background of this implementation?

### ISSUE THREAD

**Issue by christianparpart** [ldez/cubejs#116]
Hey.

Many thanks for this great project! I would love to better understand how to implement a cube solver / state generator , and so found you. I am not a CoffeeScript guy, but the code seems somewhat readable still.

In order to better understand, I was wondering what your implementation is based on. Is there some paper to read or anything that helps better understanding this implementation 's background?

Many thanks,
Christian.

**Comment by ldez** [comment]
Hello, it's in the [readme](https://github.com/ldez/cubejs): http://kociemba.org/cube.htm
