### ISSUE TITLE
Not generating scrambles with odd parity

### ISSUE THREAD

**Issue by pedroteosousa** [ldez/cubejs#14]

**Comment by ldez** [comment]
Could give more information? examples?

**Comment by pedroteosousa** [comment]
I generated about a thousand cubes with Cube.random() and checked the number of edge swaps to solve the cube using BLD, and all of them turned out even.

**Comment by pedroteosousa** [comment]
Just noticed that in random() there is a part that ensures an even number of swaps, but a cube is still valid if both edges and corners have an odd number of swaps
