### ISSUE TITLE
Cube.fromString(str) doesn't work properly

### ISSUE THREAD

**Issue by HannesMatthias** [ldez/cubejs#16]
If I scan my current solved cube then I use Cube.fromString(mystring), then it returns false when I do cube.isSolved();

Thanks

MH-Team

**Comment by HannesMatthias** [comment]
I use this api to scan my cube -> https://github.com/hakatashi/giiker

**Comment by ldez** [comment]
Could you give me some data to validate this behavior?

**Comment by HannesMatthias** [comment]
You are very fast. I'm closing the issue.
Sorry, it was the error from the other api.


Thank you for providing this API.



Am So., 2. Dez. 2018, 20:04 hat Ludovic Fernandez <notifications@github.com>
geschrieben:
