### ISSUE TITLE
Convert to notation

### ISSUE THREAD

**Issue by jawadcode** [ldez/cubejs#82]
there is no simple way to output the scramble as normal Rubik's cube notation AFAIK, but if there is please tell me

**Comment by ldez** [comment]
Hello,

cube.js is a modeler and a solver, but not a scrambler.

If you are looking for a scrambler, take a look the WCA approved scrambler: https://github.com/cubing/jsss

**Comment by jawadcode** [comment]
I have checked out jsss but the canvas feature doesn't seem to work for me.
