### ISSUE TITLE
Question: Do the solves ever contain M,E or S?

### ISSUE THREAD

**Issue by Booligoosh** [ldez/cubejs#9]
Hi Idez,
Thanks for your awesome work.
Just a question: do the solves ever contain M,E or S?
I'm making a Rubik's Cube solving robot and I need to know if these will ever occur so I can convert it into moving the other two layers then rotating the cube.

Thanks,
Booligoosh

**Comment by akheron** [comment]
No it doesn't. Only U, R, F, D, L and B.
